# Конфигурационный файл для AutoBlock плагина
# Формат: <ключ>: <добываемый предмет>: <результирующий предмет>: <необходимое количество>: <количество результата>

# Пример для алмазов:
# При добыче алмазной руды (diamond_ore) будет проверяться инвентарь на наличие 9 алмазов (DIAMOND).
# Если алмазов достаточно, они будут преобразованы в 1 алмазный блок (DIAMOND_BLOCK).

diamond_ore: DIAMOND:DIAMOND_BLOCK:9:1

# Пример для золота:
# При добыче золотой руды (gold_ore) будет проверяться инвентарь на наличие 9 золотых слитков (GOLD_INGOT).
# Если слитков достаточно, они будут преобразованы в 1 золотой блок (GOLD_BLOCK).

gold_ore: GOLD_INGOT:GOLD_BLOCK:9:1

# Пример для железа:
# При добыче железной руды (iron_ore) будет проверяться инвентарь на наличие 9 железных слитков (IRON_INGOT).
# Если слитков достаточно, они будут преобразованы в 1 железный блок (IRON_BLOCK).

iron_ore: IRON_INGOT:IRON_BLOCK:9:1
